### PR TITLE
port to LLVM 9.0.1

### PR DESCRIPTION
**Pull request by korli**

### CODE REVIEW

**Comment by owenca** [comment]
@korli thanks! I will look into this sometime this week.

**Comment by korli** [comment]
I would consider to remove this commit: "Always remove redundant braces of a control statement".
Indeed I wasn't really pleased with it when testing with a few HaikuArchives projects.

**Comment by pulkomandy** [comment]
I have ported this patch to clang-format 11. I confirm that removal of braces is currently way too agressive. I tested it on src/kits/interface/View.cpp in Haiku and it seems to remove braces that are not redundant at all. It seems confused in particular when there are nested if/else statements.

**Comment by owenca** [comment]
@pulkomandy I ran into the following errors while building LLVM 11.0.0 on Haiku R1/beta2 64-bit:
```
In file included from /boot/home/haiku-format/llvm-project/llvm/lib/Support/Program.cpp:99:
/boot/home/haiku-format/llvm-project/llvm/lib/Support/Unix/Program.inc:335:9: error: '::wait4' has not been declared
 using ::wait4;
         ^~~~~
/boot/home/haiku-format/llvm-project/llvm/lib/Support/Unix/Program.inc: In function 'llvm::sys::ProcessInfo llvm::sys::Wait(const llvm::sys::ProcessInfo&, unsigned int, bool, std::string*, llvm::Optional<llvm::sys::ProcessStatistics>*)':
/boot/home/haiku-format/llvm-project/llvm/lib/Support/Unix/Program.inc:408:27: error: 'wait4' is not a member of 'llvm::sys'
     WaitResult.Pid = sys::wait4(ChildPid, &status, WaitPidOptions, &Info);
                           ^~~~~
/boot/home/haiku-format/llvm-project/llvm/lib/Support/Unix/Program.inc:408:27: note: suggested alternative: 'Wait'
     WaitResult.Pid = sys::wait4(ChildPid, &status, WaitPidOptions, &Info);
                           ^~~~~
                           Wait
/boot/home/haiku-format/llvm-project/llvm/lib/Support/Unix/Program.inc:451:54: error: 'struct rusage' has no member named 'ru_maxrss'
     uint64_t PeakMemory = static_cast<uint64_t>(Info.ru_maxrss);
                                                      ^~~~~~~~~
```

**Comment by pulkomandy** [comment]
wait4 is available in Haiku since 2009: https://git.haiku-os.org/haiku/commit/?id=ada17216f977d9c02262744ea553da5675340865 but may need the -D_BSD_SOURCE compiler flag or #define _BSD_SOURCE in the affected file.

ru_maxrss does not exist in Haiku and is not specified in POSIX: https://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/resource.h.html

I only tested from Linux, some extra patching seems needed for building in Haiku.

**Comment by owenca** [comment]
I tried building LLVM 10.0.1 (on Haiku hrev54741 x86_64) and it worked. Will continue with 10.0.1 for now.

**Pull request merged**
